// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Challenge
{
    public partial class Student
    {
        public Student()
        {
            StudentPaids = new HashSet<StudentPaid>();
        }

        [Key]
        public Guid StudentID { get; set; }
        public int StudentNumber { get; set; }
        [StringLength(50)]
        public string StudentName { get; set; }
        [StringLength(50)]
        public string StudentSurname { get; set; }

        [InverseProperty(nameof(StudentPaid.Student))]
        public virtual ICollection<StudentPaid> StudentPaids { get; set; }
    }
}