// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Challenge
{
    [Table("StudentPaid")]
    public partial class StudentPaid
    {
        [Key]
        public Guid StudentPaidID { get; set; }
        public Guid StudentID { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? StudentPaidDetail { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StudentPaidDate { get; set; }

        [ForeignKey(nameof(StudentID))]
        [InverseProperty("StudentPaids")]
        public virtual Student Student { get; set; }
    }
}